name: Tests

on: [pull_request, push, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Check build, markup, and links
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        os: [macos-latest, ubuntu-latest]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install uv
        uses: hynek/setup-cached-uv@v2
      - name: Build docs
        run: make html
      - name: Link check
        run: make linkcheck
        continue-on-error: true
